# Generated by Django 2.2.5 on 2019-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('stu_id', models.CharField(max_length=48)),
                ('major', models.CharField(max_length=48)),
                ('qq', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('something', models.CharField(max_length=512)),
            ],
        ),
    ]
